from setuptools import setup

setup(
    name="inamta-flasher",
    version="0.4.3",
    description="Python test package",
    license="Apache Software License (http://www.apache.org/licenses/LICENSE-2.0)",
    author="Moritz Ulmer",
    packages=["src"],
    install_requires=[
        "appdirs==1.4.4",
        "bitarray==2.8.1",
        "bitstring==4.1.1; python_version >= '3.7'",
        "certifi==2023.7.22; python_version >= '3.6'",
        "cffi==1.15.1",
        "charset-normalizer==3.2.0; python_version >= '3.7'",
        "cryptography==41.0.3; python_version >= '3.7'",
        "ecdsa==0.18.0; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "esptool==4.6.2",
        "idna==3.4; python_version >= '3.5'",
        "importlib-metadata==6.8.0; python_version < '3.12'",
        "jaraco.classes==3.3.0; python_version >= '3.8'",
        "jeepney==0.8.0; sys_platform == 'linux'",
        "keyring==24.0.1",
        "littlefs-python==0.4.0",
        "more-itertools==10.1.0; python_version >= '3.8'",
        "pycparser==2.21",
        "pyjwt[crypto]==2.7.0",
        "pyserial==3.5",
        "pyside6==6.4.3",
        "pyside6-addons==6.4.3; python_version < '3.12' and python_version >= '3.7'",
        "pyside6-essentials==6.4.3; python_version < '3.12' and python_version >= '3.7'",
        "pyyaml==6.0.1; python_version >= '3.6'",
        "reedsolo==1.7.0",
        "requests==2.31.0",
        "secretstorage==3.3.3; sys_platform == 'linux'",
        "semantic-version==2.10.0",
        "shiboken6==6.4.3; python_version < '3.12' and python_version >= '3.7'",
        "six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "urllib3==2.0.4; python_version >= '3.7'",
        "zipp==3.16.2; python_version >= '3.8'",
    ],
    entry_points={"console_scripts": ["inamata-flasher=main:main"]},
    classifiers=[
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.10",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX",
        "License :: OSI Approved :: Apache Software License",
    ],
)
