name: inamata-flasher
title: Inamata Flasher
summary: A microcontroller flasher for the Inamata IoT platform
description: |
  Flash the Inamata firmware on microcontrollers (ESP32) and register them
  on the Inamata IoT platform. Allows preconfiguring WiFi connections,
  naming the device selecting the firmware to be used.

  Note that USB devices are not hot-pluggable in snap applications. The
  executable on the release page does not have this limitation. Also the
  following commands have to be executed in a terminal to access the USB
  devices and save refresh tokens in the system's keyring.

  Required:
    sudo snap connect inamata-flasher:raw-usb

  Optional:
    sudo snap connect inamata-flasher:password-manager-service
license: Apache-2.0
version: 1.3.1
grade: stable
confinement: strict
base: core22
icon: snap/gui/inamata-flasher.svg
architectures:
  - build-on: amd64
compression: lzo
contact: moritz@silentwind.eu
issues: https://github.com/InamataIO/Flasher/issues
source-code: https://github.com/InamataIO/Flasher/
website: https://www.inamata.io/

apps:
  inamata-flasher:
    command: bin/inamata-flasher
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - password-manager-service
      - removable-media
      - raw-usb
      - serial-port
      - x11

parts:
  inamata-flasher:
    plugin: python
    source: .
    #    source: https://github.com/InamataIO/Flasher.git
    stage-packages:
      - libcairo2
      - libcairo-gobject2
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libfontconfig1
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libwayland-cursor0
      - libwayland-server0
      - libx11-6
      - libxcb-icccm4
      - libxi6
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxkbfile1
      - libxtst6
      - libxcomposite1
      - libxdamage1
      - libxcb-cursor0
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xkb1
      - libxkbcommon-x11-0
